const hoitoOhjeet: { [key: string]: string } = {
  Tuoli:
    "Furniture made of solid wood has many esthetic and performance related benefits, which need to be maintained with proper care. Please notice, that cold and dry winter climate together with the heating indoors creates very dry environment which can be unhealthy to people as well as the furniture of the house. Also, during very humid months the furniture may suffer without proper care. In dry winter climate the wood may shrink. This causes cracks, which is a very natural reacti on of the wood to its environment. This kind of cracks will usually disappear when the climate turns more humid and the wood swells. However, if you notice a crack between two planks showing a separation of a glue line, please contact us. In very humid tim es the wood might swell and cause problems with moving parts such as drawers. In these cases the wood will slowly shrink back to original dimensions once the climate becomes dryer.",
  Ulkokäytössä:
    "We use wood oil for outdoors as the surface treatment material. It is highly recommended to prevent the surfaces from becoming wet by wiping them clean and dry as soon as possible when they have been left in the rain. We kindly ask you to acknowledge, that the UV Protection Oil helps to maintain the origina l colouring of the wood. However, little by little wood begins to gray outdoors. The graying process is unique with each product, and in between the colours the wooden surface might look odd with all the dots and spots. All our terrace furniture is designed keeping this graying process in mind: they will look absolutely beautiful when totally gray, and the durability of the joints will not be affected throughout the color change. We recommend moving the furniture indoors well in advance before the rainy season begins. We recommend oiling the furniture regularly . In case the products stay outside throughout the summer, they usually n eed treatment every year. When you start, please rem ove all the dirt from wood. You can then add OsmoColor UV Protection Oil to the dry and clean surface. Please follow the instructions on the packaging carefully. NB: Oak wood is very sensitiv e to iron oxide. The i ron particles in the air are very efficient in making dark spots , when they mix with water on the surface of the wood material . As a consequence the surface develop s black spots or bigger dark areas. This doesn ’t affect the the durability of the material.",
  leather:
    "As with any other material for interior design, a laminate surface should be cleaned regularly. It does not require any special maintenance, just a damp cloth with warm water or a mild detergent. Almost all regular household cleaning products or disinfectants can be safely used. For the most common stains, you can simply clean the surface with warm water using a non - abrasive cloth. Tougher stains can be removed with non - a brasive household cleaners or solvents. For older, dried or caked - on stains, use a magic sponge or soft cloth to remove them. After using any solvents, we recommend rinsing the surface with warm water and a detergent. Always rinse thoroughly to remove the detergent with clean water, preferably warm.",
  wood: "We use natural wood oil mixtures as the surface finish. Please note that you should always wipe the surface clean and dry of any liquids as soon as possible (in 15 minutes). Clean the surface normally with a damp cloth, using organic soaps. In order to keep your table in be st possible condition, you should clean the table top with the very finest sandy cloth once in two years. After that, treat the table top with a natural matte wood oil or wax. Let the oil - wax impregnate for 15 - 20 min, and wipe the rest off. Use a clean clo th to finish and polish the surface in the end. Please follow the instructions of the surface finish oil mixture product you are using . ( Natural treatment sprays can be used as well. NB: do not use silicone based or other non - natural treatment oils or waxes. ) In c ase your product is treated with stain and/or ( water - based ) lacquer , it is good to know that the lacquer keeps the wooden surface protected of liquids and dirt very effectively. When some spilling or staining occurs, i t is recommended to wipe it clean and dry quickly with a damp cloth, using organic soaps. In case the water - based lacquer surface is damaged, it should be sanded and the lacquer treatment redone.",
  Sisäkäytössä:
    "Leather is a natural material. With correct care and maintenance premium vegetable tanned leather will age gracefully, developing a beautiful patina with use over time. General advice Exposure to direct sunlight will darken “blonde” colors an d bleach darker colors. Hot, dry air can dry out leather if it is not regularly conditioned. Certain chemicals and detergents can damage the surfac e of the leather and tarnish the color. Cleaning Anytime that your leather is stained or when it has dried out after being wet repeat step 1 and 2. Over time you will develop your own “hand feel” for when cleaning or care is needed. STEP 1: Remove any dirt or stains with a clean natural spon ge or soft cloth before applying any oils or condit ioners. Varieties of leather leaning products are available and can be divided into two groups distinguished b y their active ingredients: - Surfectants that clean the surface of the leather - Leather soaps that deep clean Try both types of cleaners to find your preference. STEP 2: After cleaning, it is important to apply something that will nourish the leather, protect it and help it to retain moisture. Use a product that contains a natural wax. The wax will protect t he leather in the same way that wax protects the pa int of a car",
};

export default hoitoOhjeet;